version: "3"
services:
  server:
    build:  ./BEnd
    container_name: "server_cnt"
    ports: 
      - "5000:5000"
    volumes: 
      - ./BEnd:/app
    environment: 
      FLASK_ENV: development
    depends_on:
      - db
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db/:/app/container_db
  client:
    build: ./my_app
    container_name: "client_cnt"
    ports: 
      - "3000:3000"
    depends_on: 
      - server